### ISSUE TITLE
Query Regarding Update to Collabora Version 24

### ISSUE THREAD

**Issue by javiloncho** [mother-of-all-self-hosting/ansible-role-collabora-online#2]
Hello,

I am currently using Collabora and I am interested in knowing if there are any plans to update to version 24. This update is important for us due to the new features and improvements it offers.

Could you please provide any information on whether this update is scheduled ?

Thank you for your support and for the continuous improvement of the software.

**Comment by spantaleev** [comment]
You can try adding something like `collabora_online_version: 24.04.3.1.1` to your `vars.yml` file and re-running the playbook.

I'm not sure if that's all that's necessary for a successful upgrade, but you can try and let us know! If so, we can bump the version for everyone in `defaults/main.yml`.

**Comment by javiloncho** [comment]
I've updated the version in the `vars.yml` file and everything has worked correctly after the upgrade. No further changes are needed.

Thank you so much!
